services:
  # A Rails web service
  - type: web
    name: Rails
    env: ruby
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
