services:
  # Rails API
  - type: web
    name: era-api
    env: ruby
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    healthCheckPath: /healthz
    envVars:
      - key: DATABASE_USER
        ync: false
      - key: DATABASE_PASSWORD
        sync: false
      - key: DATABASE_HOST
        sync: false
      - key: DATABASE_PORT
        sync: false
      - key: RAILS_MASTER_KEY
        sync: false
  # Frontend
  - type: web
    name: era-frontend
    env: static
    branch: main
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    headers:
      - path: /*
        name: X-Frame-Options
        value: sameorigin
