services:
  # Rails API
  - type: web
    name: era-api
    env: ruby
    region: singapore
    plan: free
    branch: main
    rootDir: backend
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: era_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  # Frontend
  - type: web
    name: era
    env: static
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
